import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin={"true"}
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap'
          rel='stylesheet'
        />
      </Head>
      <div style={{ marginTop: 96 }}>
        <img
          src='/Photo.png'
          style={{ width: "90px", height: "90px", borderRadius: "100%" }}
        />
      </div>
      <h1>Hi, I'm Aleksandr 👋</h1>
      <p>
        I'm passionate about web development, open-source software and UI
        design.
      </p>
      <p style={{ marginBottom: 42 }}>
        Currently working at{" "}
        <a
          style={{ color: "lightblue", textDecoration: "underline" }}
          href='https://dreambroker.com'
        >
          Dream Broker Oy
        </a>{" "}
        as a Junior Software Engineer.
      </p>
      <h3 style={{ marginBottom: 4 }}>Find me at:</h3>
      <ul
        style={{
          listStyleType: "none",
          margin: 0,
          padding: 0,
          marginBottom: 64,
        }}
      >
        <li style={{ marginBottom: "24px", marginTop: 12 }}>
          <a
            style={{ color: "#ea4c89", textDecoration: "underline" }}
            href='https://dribbble.com/AleksandrShchilkin'
          >
            Dribbble
          </a>
        </li>
        <li style={{ margin: "24px 0" }}>
          <a
            style={{ textDecoration: "underline" }}
            href='https://github.com/shchilkin'
          >
            GitHub
          </a>
        </li>
        <li style={{ margin: "24px 0" }}>
          <a
            style={{ color: "#0077b5", textDecoration: "underline" }}
            href='https://www.linkedin.com/in/aleksandrshchilkin/'
          >
            LinkedIn
          </a>
        </li>
      </ul>
      <a
        style={{
          padding: "16px 32px",
          backgroundColor: "#606060",
          borderRadius: 12,
        }}
        href='mailto:shchilkin@gmail.com'
      >
        Contact me
      </a>
    </div>
  );
}
